version: '3.2'

services:
  nginx:
    image: nginx:1.17
    ports:
      - 4000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  influxdb:
    image: influxdb:1.7
    expose:
      - 8086
    environment:
      - 'INFLUXDB_DB=metrics'
      - 'INFLUXDB_ADMIN_USER=admin'
      - 'INFLUXDB_ADMIN_PASSWORD=123'
      - 'INFLUXDB_USER=user'
      - 'INFLUXDB_USER_PASSWORD=123'
    volumes:
      - influx-data:/var/lib/influxdb

volumes:
  influx-data: